name: Docker

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "**.yml"
      - "**.yaml"
      - "**.md"
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [update]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}-ci
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
      packages: write
    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Output Variables
        id: var
        run: |
          nginx_v=$(grep -m1 "FROM nginx:" <Dockerfile | awk -F"[: ]" '{print $3}')
          docker pull nginx:"${nginx_v}" || exit 1
          njs=$(docker run nginx:"${nginx_v}" env | grep NJS_VERSION | cut -d= -f2)
          echo "NJS_VERSION=${njs}"
          echo "nginx_version=${nginx_v}" >> "$GITHUB_OUTPUT"
          echo "njs_version=${njs}" >> "$GITHUB_OUTPUT"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          buildkitd-flags: --debug
          driver-opts: network=host

      - name: DockerHub Login
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name != 'pull_request'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            name=nginxcontrib/nginx-ubi,enable=${{ github.event_name != 'pull_request' }}
            name=ghcr.io/lucacome/nginx-ubi,enable=${{ github.event_name != 'pull_request' }}
            name=localhost:5000/nginx-ubi/local-ubi
          tags: |
            type=raw,value=${{ steps.var.outputs.nginx_version }}

      - name: Build from source
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: build
        with:
          pull: true
          push: true
          platforms: "linux/ppc64le, linux/s390x"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=source
          cache-to: type=gha,scope=source,mode=max
          target: final
          provenance: mode=max
          sbom: true
          build-args: |
            NGINX=${{ steps.var.outputs.nginx_version }}
            NJS=${{ steps.var.outputs.njs_version }}

      - name: Build prebuilt
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: build-prebuilt
        with:
          pull: true
          push: true
          platforms: "linux/amd64, linux/arm64"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=prebuilt
          cache-to: type=gha,scope=prebuilt,mode=max
          target: final
          file: Dockerfile.prebuilt
          provenance: mode=max
          sbom: true
          build-args: |
            NGINX=${{ steps.var.outputs.nginx_version }}
            NJS=${{ steps.var.outputs.njs_version }}

      - name: Combine images
        run: |
          docker buildx imagetools create nginxcontrib/nginx-ubi@${{ steps.build.outputs.digest }} ${{ steps.build-prebuilt.outputs.digest }} --tag nginxcontrib/nginx-ubi:${{ steps.meta.outputs.version }}
          docker buildx imagetools create nginxcontrib/nginx-ubi:${{ steps.meta.outputs.version }} --tag nginxcontrib/nginx-ubi:latest
          docker buildx imagetools create nginxcontrib/nginx-ubi:${{ steps.meta.outputs.version }} --tag nginxcontrib/nginx:latest-ubi
          docker buildx imagetools create nginxcontrib/nginx-ubi:${{ steps.meta.outputs.version }} --tag nginxcontrib/nginx:${{ steps.meta.outputs.version }}-ubi

          docker buildx imagetools create ghcr.io/lucacome/nginx-ubi@${{ steps.build.outputs.digest }} ${{ steps.build-prebuilt.outputs.digest }} --tag ghcr.io/lucacome/nginx-ubi:${{ steps.meta.outputs.version }}
          docker buildx imagetools create ghcr.io/lucacome/nginx-ubi:${{ steps.meta.outputs.version }} --tag ghcr.io/lucacome/nginx-ubi:latest
          docker buildx imagetools create ghcr.io/lucacome/nginx-ubi:${{ steps.meta.outputs.version }} --tag ghcr.io/lucacome/nginx:latest-ubi
          docker buildx imagetools create ghcr.io/lucacome/nginx-ubi:${{ steps.meta.outputs.version }} --tag ghcr.io/lucacome/nginx:${{ steps.meta.outputs.version }}-ubi
        if: github.event_name != 'pull_request'

      - name: Inspect SBOM and output manifest
        run: |
          docker buildx imagetools inspect localhost:5000/nginx-ubi/local-ubi:${{ steps.meta.outputs.version }} --format '{{ json (index .SBOM "linux/amd64").SPDX }}' > sbom.json
          docker buildx imagetools inspect localhost:5000/nginx-ubi/local-ubi:${{ steps.meta.outputs.version }} --raw

      - name: Scan SBOM
        id: scan
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          sbom: "sbom.json"
          only-fixed: true
          add-cpes-if-none: true
          fail-build: false

      - name: Upload scan result to GitHub Security tab
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        continue-on-error: true
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
        if: always()

      - name: Upload Scan Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        continue-on-error: true
        with:
          name: scan-results
          path: |
            ${{ steps.scan.outputs.sarif }}
            *.json
        if: always()
